
mgfxc DefaultContentSource/effects/Bevels.fx DefaultContent/effects/Bevels.mgfxo 
mgfxc DefaultContentSource/effects/BloomCombine.fx DefaultContent/effects/BloomCombine.mgfxo 
mgfxc DefaultContentSource/effects/BloomExtract.fx DefaultContent/effects/BloomExtract.mgfxo 
mgfxc DefaultContentSource/effects/Crosshatch.fx DefaultContent/effects/Crosshatch.mgfxo 
mgfxc DefaultContentSource/effects/DeferredLighting.fx DefaultContent/effects/DeferredLighting.mgfxo 
mgfxc DefaultContentSource/effects/DeferredSprite.fx DefaultContent/effects/DeferredSprite.mgfxo 
mgfxc DefaultContentSource/effects/Dissolve.fx DefaultContent/effects/Dissolve.mgfxo 
mgfxc DefaultContentSource/effects/Dots.fx DefaultContent/effects/Dots.mgfxo 
mgfxc DefaultContentSource/effects/ForwardLighting.fx DefaultContent/effects/ForwardLighting.mgfxo 
mgfxc DefaultContentSource/effects/GaussianBlur.fx DefaultContent/effects/GaussianBlur.mgfxo 
mgfxc DefaultContentSource/effects/Grayscale.fx DefaultContent/effects/Grayscale.mgfxo 
mgfxc DefaultContentSource/effects/HeatDistortion.fx DefaultContent/effects/HeatDistortion.mgfxo 
mgfxc DefaultContentSource/effects/Invert.fx DefaultContent/effects/Invert.mgfxo 
mgfxc DefaultContentSource/effects/Letterbox.fx DefaultContent/effects/Letterbox.mgfxo 
mgfxc DefaultContentSource/effects/MultiTexture.fx DefaultContent/effects/MultiTexture.mgfxo 
mgfxc DefaultContentSource/effects/MultiTextureOverlay.fx DefaultContent/effects/MultiTextureOverlay.mgfxo 
mgfxc DefaultContentSource/effects/Noise.fx DefaultContent/effects/Noise.mgfxo 
mgfxc DefaultContentSource/effects/PaletteCycler.fx DefaultContent/effects/PaletteCycler.mgfxo 
mgfxc DefaultContentSource/effects/PixelGlitch.fx DefaultContent/effects/PixelGlitch.mgfxo 
mgfxc DefaultContentSource/effects/PolygonLight.fx DefaultContent/effects/PolygonLight.mgfxo 
mgfxc DefaultContentSource/effects/Reflection.fx DefaultContent/effects/Reflection.mgfxo 
mgfxc DefaultContentSource/effects/Scanlines.fx DefaultContent/effects/Scanlines.mgfxo 
mgfxc DefaultContentSource/effects/Sepia.fx DefaultContent/effects/Sepia.mgfxo 
mgfxc DefaultContentSource/effects/SpriteAlphaTest.fx DefaultContent/effects/SpriteAlphaTest.mgfxo 
mgfxc DefaultContentSource/effects/SpriteBlinkEffect.fx DefaultContent/effects/SpriteBlinkEffect.mgfxo 
mgfxc DefaultContentSource/effects/SpriteEffect.fx DefaultContent/effects/SpriteEffect.mgfxo 
mgfxc DefaultContentSource/effects/SpriteLightMultiply.fx DefaultContent/effects/SpriteLightMultiply.mgfxo 
mgfxc DefaultContentSource/effects/SpriteLines.fx DefaultContent/effects/SpriteLines.mgfxo 
mgfxc DefaultContentSource/effects/StencilLight.fx DefaultContent/effects/StencilLight.mgfxo 
mgfxc DefaultContentSource/effects/Twist.fx DefaultContent/effects/Twist.mgfxo 
mgfxc DefaultContentSource/effects/Vignette.fx DefaultContent/effects/Vignette.mgfxo 
mgfxc DefaultContentSource/effects/transitions/Wind.fx DefaultContent/effects/transitions/Wind.mgfxo 
mgfxc DefaultContentSource/effects/transitions/TextureWipe.fx DefaultContent/effects/transitions/TextureWipe.mgfxo 
mgfxc DefaultContentSource/effects/transitions/Squares.fx DefaultContent/effects/transitions/Squares.mgfxo 
